### ISSUE TITLE
使用的.mflac文件必须是frida attach上的这个qq音乐下载的吗？

### ISSUE THREAD

**Issue by imrenyujing** [yllhwa/decrypt-mflac-frida#11]
我有朋友从mac qq音乐上下载下来的.mflac文件，在windows上使用qq音乐 20.43版本能够解密出flac文件，但无法播放。是标题说的原因吗？还是此版本代码已经无法适用20.43版本的qq音乐。

**Comment by yllhwa** [comment]
是的，只能解密本机下载的 mflac
