### ISSUE TITLE
提示错误.如何解决 

### ISSUE THREAD

**Issue by oliverlee88** [yllhwa/decrypt-mflac-frida#4]
Decrypting 海来阿木 - 西楼儿女_EM.mflac

(process:25356): GLib-GIO-WARNING **: 21:56:03.973: _g_dbus_worker_do_read_cb: error determining bytes needed: Blob indicates that message exceeds maximum message length (128MiB)
Traceback (most recent call last):
  File "C:\Users\15109\Desktop\decrypt-mflac-frida-main\hook_qq_music.py", line 41, in <module>
    data = script.exports_sync.decrypt(os.path.join(root, file))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15109\AppData\Roaming\Python\Python312\site-packages\frida\core.py", line 180, in method
    return script._rpc_request(request, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15109\AppData\Roaming\Python\Python312\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\15109\AppData\Roaming\Python\Python312\site-packages\frida\core.py", line 497, in _rpc_request
    raise result.error
frida.InvalidOperationError: script has been destroyed

PS C:\Users\15109\Desktop\decrypt-mflac-frida-main> pip show frida
Name: frida
Version: 16.4.4
Summary: Dynamic instrumentation toolkit for developers, reverse-engineers, and security researchers
Home-page: https://frida.re
Author: Frida Developers
Author-email: oleavr@frida.re
License: wxWindows Library Licence, Version 3.1
Location: C:\Users\15109\AppData\Roaming\Python\Python312\site-packages
Requires:
Required-by:

PS C:\Users\z1595\Desktop\decrypt-mflac-frida-main\decrypt-mflac-frida-main> Python -V
Python 3.12.3

**Comment by yllhwa** [comment]
QQ音乐版本？

**Comment by oliverlee88** [comment]
> QQ音乐版本？

20.31
19.51
感谢您的回复，二种都试过，都是同样的问题。这是什么原因呢，找过GPT,它改了好多版本，没找到原因...

**Comment by yllhwa** [comment]
尝试升级到最新版本

**Comment by HHxiaoxiong** [comment]
> 尝试升级到最新版本

没有效果的，我这边测试好像是mflac文件大于128MB就会出现这个错误，大概在js返回到python的时候就会出错

**Comment by yllhwa** [comment]
fixed

**Comment by HHxiaoxiong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
