### ISSUE TITLE
解码后专辑图片消失了

### ISSUE THREAD

**Issue by DeeChael** [yllhwa/decrypt-mflac-frida#6]
在同专辑下一部分歌曲为 VIP 歌曲，一部分为 VIP，打开非 VIP 歌曲可以看到专辑图片被正常下载，但是如果使用该工具解密后被解密的 VIP 歌曲的专辑图片却无法显示。  
使用 Potplayer 播放，将窗口最大化即可看到专辑图片。  
虽然是个无关紧要的功能，但是对于我这种想要收藏歌曲的人来说最好还是有专辑封面的。

**Comment by DeeChael** [comment]
![image](https://github.com/user-attachments/assets/0585a071-c71b-4093-902b-c4dc0ff84817)
以 HoYo-MiX 的 崩坏3-Onwards-Original Soundtrack 专辑为例，同一首歌的伴奏和原版。  
左边为伴奏版，非 VIP 歌曲，专辑封面正常。右边为原版，VIP 歌曲，专辑封面丢失。

**Comment by DeeChael** [comment]
其实也有一种可能是 qq 根本没往 mflac 格式的文件里塞专辑封面，还有劳各位研究一下了

**Comment by yanleiberg** [comment]
看了下代码，是使用QQ自己的解密函数的，所以没有专辑封面也算正常，推荐使用 音乐标签 软件来补封面。  https://www.cnblogs.com/vinlxc/p/11347744.html

**Comment by DeeChael** [comment]
OK
